### ISSUE TITLE
ImportError: No module named 'scenenet_pb2'

### ISSUE THREAD

**Issue by amiltonwong** [jmccormac/pySceneNetRGBD#1]
Hi, @jmccormac , @ankurhanda ,

After running "python3 read_protobuf.py", I got:
ImportError: No module named 'scenenet_pb2', it seems scenenet_pb2 module is missing.

Have a look ~
Thanks~

**Comment by ankurhanda** [comment]
Did you make? there is a Makefile in that directory.

**Comment by amiltonwong** [comment]
Thanks @ankurhanda for very quick reply.
Got scenenet_pb2 module now, after command "make"

THX!
