### ISSUE TITLE
Floor plans from SceneNet

### ISSUE THREAD

**Issue by preddy5** [jmccormac/pySceneNetRGBD#10]
https://drive.google.com/open?id=0B_CLZMBI0zcuRmM4cDIzdUtSdUU link present on https://robotvault.bitbucket.io/scenenet-rgbd.html is empty. I couldn't find the code in the repository to generate floor plans myself. Is there some way I can generate them myself.

Thank you,
Pradyumna.

**Comment by ankurhanda** [comment]
The link does have everything you need - maybe permissions issue. Here is the link https://drive.google.com/open?id=0B_CLZMBI0zcublNiQWFCVEYzZGM. There is no code to generate floor plans. It has scenenet_layout.tgz that contains the floor plans you need and texture_library.tgz for adding textures, if that's what you are looking for.

**Comment by preddy5** [comment]
Hi Ankur,
Thank you for you response. I am unable to access the directory in google drive you shared above it says "We're sorry. You can't access this item because it is in violation of our Terms of Service." 

Could you suggest what is a good place to start if I want to write a script myself to generate the floor plans.

Thank you,
Pradyumna.

**Comment by ankurhanda** [comment]
now https://drive.google.com/drive/folders/0B_CLZMBI0zcuRmM4cDIzdUtSdUU?usp=sharing ?

**Comment by preddy5** [comment]
![image](https://user-images.githubusercontent.com/2454021/33176470-11517382-d057-11e7-868f-96c5a05b38eb.png)

**Comment by ankurhanda** [comment]
<img width="706" alt="screen shot 2017-11-23 at 14 04 02" src="https://user-images.githubusercontent.com/686480/33176526-3ba960cc-d057-11e7-83f9-61f868a3d15b.png">

**Comment by ankurhanda** [comment]
I gave you access to your gmail account.

**Comment by ankurhanda** [comment]
if that doesn't work try this https://drive.google.com/open?id=0B_CLZMBI0zcublNiQWFCVEYzZGM and https://drive.google.com/open?id=0B_CLZMBI0zcuUlNlTGlKcVk0eHc

**Comment by preddy5** [comment]
can you check if there is a untitled folder in the directory? Because the directory looks empty to me and I am show how able to create a folder with view only permissions.

![image](https://user-images.githubusercontent.com/2454021/33176862-79c3c6c6-d058-11e7-9cac-d2f9e546fc26.png)

**Comment by ankurhanda** [comment]
No idea --- I will look into it later tonight!

**Comment by preddy5** [comment]
Sure, thank you for the response.

**Comment by ankurhanda** [comment]
I moved them to new directories and see if you can access them. I sent links to your gmail.

**Comment by preddy5** [comment]
I can access them now, thanks Ankur :)

**Comment by laurimi** [comment]
Hi @ankurhanda - I am suffering from this issue as well, the directory looks empty to me both logged in and not logged in. Would really appreciate it if you could assist in obtaining the floor plans!

**Comment by ankurhanda** [comment]
Can you give me your email id?

**Comment by laurimi** [comment]
@ankurhanda sent to you via email at your GitHub profile listed email.

**Comment by ankurhanda** [comment]
I didn't get it
