### ISSUE TITLE
depth definition

### ISSUE THREAD

**Issue by versatran01** [jmccormac/pySceneNetRGBD#17]
I'm a bit confused about how to interpret depth from the dataset.
The paper says 
> Depth is defined as the ray length from the camera origin to the first surface it intersects with

From my understanding, this is different from the depth map. Please advise.

**Comment by jmccormac** [comment]
Yes the use of euclidean depth here is different from the depth image produced from say a Kinect RGB-D camera. The depth values in a kinect measures the z-axis component of the point in the camera coordinate frame.  A diagram showing that is available [here](https://msdn.microsoft.com/en-gb/library/hh438997.aspx)

Basically if the camera views a flat wall head-on, in this dataset the corners of the image will be at a greater euclidean distance (the hypotenuse) than the center, but in a kinect camera they will all have the same depth values which is the distance the wall is along the z-axis (the adjacent).
