### ISSUE TITLE
how do we generate optical flow from the dataset?

### ISSUE THREAD

**Issue by tsaizhenling** [jmccormac/pySceneNetRGBD#2]

**Comment by jmccormac** [comment]
Sorry for the late reply.  The way that we calculated optical flow is to use the depth image and camera poses to calculate the 3D points associated with each pixel in world coordinates.  We then calculate the instantaneous derivatives of those points projection into pixel space over time halfway through the shutter exposure trajectory (i.e. where the ground truth was taken).

I will shortly clean up and push a script that outputs a hsv image of optical flow from the calculated derivatives for a randomly selected trajectory.

**Comment by jmccormac** [comment]
The calculate_optical_flow.py script has now been added to the repo.

**Comment by tsaizhenling** [comment]
much appreciated!
