### ISSUE TITLE
Generate scene as .obj + .mtl 

### ISSUE THREAD

**Issue by arnovaill** [jmccormac/pySceneNetRGBD#31]
I am looking to generate 3D scenes from your data. I undestand that with the code you provide here: https://bitbucket.org/dysonroboticslab/scenenetrgb-d/src/master/ you can generate randomly a scene and a trajectory in it. Is there any way to get the obtained scene as .obj + .mtl file from the obtained scene_and_trajectory_description.txt file ? Thank you!

**Comment by ankurhanda** [comment]
The function to create a new obj out of the txt files does not exist in the repo. However, the function shouldn't be hard to implement as you only need to transform the objects given their poses and put it all into a single obj. You can view in meshlab if things look OK afterwards. 

Sorry that we didn't add this function into the repo.
