### ISSUE TITLE
Running error: Pangolin X11: Indirect GLX rendering context obtained

### ISSUE THREAD

**Issue by sherleens** [jmccormac/pySceneNetRGBD#32]
Hi, I am trying to generate 3D scenes from your data using code provided in https://bitbucket.org/dysonroboticslab/scenenetrgb-d/src/master/ . 
The installation is sucessful, but when I run the second step "./room_camera_intersection /path/to/your/ShapeNet/ /path/to/your/SceneNetRGBD_Layouts/ ../../scene_generator/build/scene_description.txt", something wrong happened. The error is:

Framebuffer with requested attributes not available. Using available framebuffer. You may see visual artifacts.X11 Error: GLXBadFBConfig
Pangolin X11: Indirect GLX rendering context obtained
....
Segmentation fault (core dumped)

I use MobaSterm to connect the remote ubuntu server. I want to know is it possible to generate data in this remote way?

Thanks

**Comment by ankurhanda** [comment]
OpenGL does not allow rendering with a remote connection so unfortunately it won't work for you.
