### ISSUE TITLE
Semantic Class Mapping to 37 classes?

### ISSUE THREAD

**Issue by ir0** [jmccormac/pySceneNetRGBD#7]
Hi John,

I see you have the mapping of the WordNet IDs to the 13 NYU classes. Do you have the mapping to the extended 37 classes or, if not, how I could easily get it?

Thanks!

**Comment by jmccormac** [comment]
Hi ir0,

This is a good point, unfortunately I do not have the mapping to the extended 37 classes, but the way I produced that dictionary can now be seen in the repo.  There is now a folder called ```semantic_classes``` with a script ```semantic_class_dictionary_generator.py```.  It produces the dictionary from a textfile in the same folder called ```wnid_to_class.txt``` which I have also added to the repo.

In it we manually mapped each of the wnids (using their plain english name) to the NYU 13 classes.  If you add a new column to that textfile with a custom mapping, and update the ```column_name``` and ```class_list``` variables in the ```semantic_class_dictionary_generator.py``` script, it will produce the corresponding dictionary.

Hope this is helpful, sorry we don't have the exact mapping to hand.

**Comment by ir0** [comment]
Thanks, that's helpful.

**Comment by raymond30031** [comment]
Hello @ir0 ,
Did you end up implementing the 37 classes?
Also, how did you the number 37 from?

I just downloaded the NYUDv2 dataset from [link](https://cs.nyu.edu/~silberman/datasets/nyu_depth_v2.html) and inside the mat, it looks like there are 894 classes?

**Comment by ankurhanda** [comment]
Look for those here https://github.com/ankurhanda/SceneNetv1.0/ under the section "Conversion from SUN RGB-D/NYUv2 37/40 Labels"
